"""OperationHistory changes

Revision ID: 18d3dc4c63b3
Revises: 68aaf3cadda8
Create Date: 2024-07-22 14:47:25.842119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '18d3dc4c63b3'
down_revision: Union[str, None] = '68aaf3cadda8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operation_history', 'operation_type', new_column_name='type', existing_type=sa.Integer(),
                    nullable=False)
    op.alter_column('operation_history', 'operation_data', new_column_name='data', existing_type=sa.Text(),
                    nullable=False)
    op.drop_constraint('operation_history_ibfk_1', 'operation_history', type_='foreignkey')
    op.create_foreign_key(None, 'operation_history', 'operation_types', ['type'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'operation_history', type_='foreignkey')
    op.create_foreign_key('operation_history_ibfk_1', 'operation_history', 'operation_types', ['operation_type'],
                          ['id'])
    op.alter_column('operation_history', 'type', new_column_name='operation_type', existing_type=mysql.INTEGER(),
                    nullable=False)
    op.alter_column('operation_history', 'data', new_column_name='operation_data', existing_type=mysql.TEXT(),
                    nullable=False)
    # ### end Alembic commands ###
