"""Card_update_2

Revision ID: 51a0cd70a9ce
Revises: 63ff94679af4
Create Date: 2024-08-04 15:26:54.612448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51a0cd70a9ce'
down_revision: Union[str, None] = '63ff94679af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_progress', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('cards', sa.Column('is_root', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'is_root')
    op.drop_column('card_progress', 'started_at')
    # ### end Alembic commands ###
