"""User unique ext_id

Revision ID: 63ff94679af4
Revises: 18d3dc4c63b3
Create Date: 2024-07-22 15:49:10.740694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '63ff94679af4'
down_revision: Union[str, None] = '18d3dc4c63b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'external_id',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.create_unique_constraint(None, 'users', ['external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'external_id',
               existing_type=sa.String(length=512),
               type_=mysql.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
