"""Initial commit

Revision ID: 68aaf3cadda8
Revises: 
Create Date: 2024-07-22 13:29:56.027092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68aaf3cadda8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('static_image', sa.Text(), nullable=True),
    sa.Column('animated_image', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('color', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('achievements_history', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('extended_description', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('rewardPoints', sa.Integer(), nullable=True),
    sa.Column('rewardAchievement', sa.Integer(), nullable=True),
    sa.Column('activator', sa.Text(), nullable=False),
    sa.Column('progress_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rewardAchievement'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['type'], ['card_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('operation_type', sa.Integer(), nullable=False),
    sa.Column('operation_data', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['operation_type'], ['operation_types.id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Text(), nullable=False),
    sa.Column('is_finished', sa.Boolean(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_progress')
    op.drop_table('operation_history')
    op.drop_table('cards')
    op.drop_table('users')
    op.drop_table('operation_types')
    op.drop_table('card_types')
    op.drop_table('achievements')
    # ### end Alembic commands ###
